- name: play1
  hosts: all
  tasks:
    - name: printing hello from play1
      ansible.builtin.debug:
        msg: Hello from play1
    
    - name: printing Hi from play1
      ansible.builtin.debug:
        msg: Hi from Play1

- name: play2
  hosts: node2
  tasks:
    - name: printing from node2
      ansible.builtin.debug:
        msg: Message from node2 