- name: Using Variables
  hosts: all
  vars:
    URL: play.google.com
  vars_files:
    - dev-vars.yml
  vars_prompt:
    - name: URLname
      prompt: Enter the URLname
      private: no

  tasks:
   - name: printing value of Variables
     ansible.builtin.debug:
      msg: value of url is {{URL}}

   - name: using local Variables
     ansible.builtin.debug:
      msg: value of local Variables is {{URL}}
     vars:
      URL: local.google.com

   - name: using vars files
     ansible.builtin.debug:
      msg: "{{URL}}"
  
   - name: print the prompt Variables
     ansible.builtin.debug:
      msg: url from the prompt variable is {{URLname}}