- name: using register variables
  hosts: all
  tasks:
   - name: using shell modules
     ansible.builtin.shell: uptime
     register: OUT
   - name: printing the OUT variable
     ansible.builtin.debug:
      msg: "{{OUT.stdout}}"
   - name: decalre the variables
     set_fact:
      STATUSCODE: "{{OUT.rc}}"
   - name: printing uptime command exit code
     ansible.builtin.debug:
      msg: uptime command exit code is {{STATUSCODE}}
  