- name: using register variables
  hosts: all
  tasks:
   - name: using shell modules
     ansible.builtin.shell: uptime
     register: OUT
   - name: printing the OUT variable
     ansible.builtin.debug:
      msg: "{{OUT}}"