- name: check tomact server is running or not 
  hosts: all
  tasks:
    - name: checking tomact STATUs 
      ansible.builtin.shell: ps -ef | grep java | grep -v grep
      register: OUT
      #ignore_errors: yes

    - name: starting tomact
      ansible.builtin.debug:
        msg: Starting tomact