- name: using con ditions
  hosts: all
  tasks:
   - name: run this task only on centos machines
     ansible.builtin.debug:
      msg: I am Centos machine
     when: ansible_distribution == "CentOS"
   - name: run this task only on Debian machines
     ansible.builtin.debug:
      msg: I am debian machine
     when: ansible_distribution=="Debian"