- name: using con ditions
  hosts: all
  vars:
    action: true
    bar: 
  tasks:
   - name: run this task only on centos machines
     ansible.builtin.debug:
      msg: I am Centos machine
     when: ansible_distribution == "CentOS"
   - name: run this task only on Debian machines
     ansible.builtin.debug:
      msg: I am debian machine
     when: ansible_distribution=="Debian"
   - name: using actions
     ansible.builtin.debug:
      msg: I am running this command becuase my action is true
     when: action
    - name: using bars
      ansible.builtin.debug:
        msg: "BAR is not declared"
      when: bar is undefined 
