- name: using tags
  hosts: all
  tasks:
   - name: this is front end task
     ansible.builtin.debug:
      msg: Installing Frontend
     tags: frontend
   - name: starting frontend
     ansible.builtin.debug:
      msg: Starting Frontend
     tags: frontend