- name: using privilege actions
  hosts: all
  tasks:
    - name: checking the user id 
      ansible.builtin.shell: id 
      register: OUT
    - name: Printing the user details
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"
